Algoritmo "Valor do aluguel de um automóvel"

Var
Km, Dias, Total, P1, P2: real
//o carro custa R$90 por dia e R$0,20 por Km rodado, P refere-se a esses valores
//Foi declarado pois o aplicativo não aceita multiplicação de números quebrados


Inicio
Escreva ("Quantos Km foram percorridos com o automóvel?")
Leia (Km)
Escreva ("Por quantos dias o automóvel foi alugado?")
Leia (Dias)
P1 <- 0,2
P2 <- 90
Total <- (Km*P1)+(Dias*P2)
Escreva ("Portanto o preço total a pagar é R$",Total)

Fimalgoritmo