Algoritmo "Média entre notas"

Var
 Nota1, Nota2, Md: real
 //Md - média

Inicio
  Escreva ("Digite a nota da 1ª Avaliação:")
  Leia (Nota1)
  Escreva ("Digite a nota da 2ª Avaliação:")
  Leia (Nota2)
  Md <- (Nota1 + Nota2)/ 2
     Se Md >= 7 entao
        Escreva ("Parabéns, você foi aprovado")
     Senao
          Escreva ("Infelizmente você foi reprovado")
     FimSe
    //Se a média for maior ou igual a 7 o aluno é aprovado)

Fimalgoritmo