Algoritmo "Alistamento em Relação a Idade"

Var
 Ano,Ano_atual, Idade, F, P: inteiro
 // F - quantos anos faltam, P - Quantos anos já passaram (a partir dos 18)

Inicio
 Escreva ("Digite o ano de seu nascimento:")
 Leia (Ano)
 Escreva ("Digite o ano atual:")
 Leia (Ano_atual)
 Idade <- (Ano_Atual - Ano)
 EscrevaL (" Você tem ", Idade," anos")
 F <- (18 - Idade)
 P <- (Idade - 18)
   Se Idade > 18 entao
      Escreva ("Então você deve ter se alistado há", P ," anos atrás")
   Senao
      Escreva ("Então você deve se alistar em ", F ," anos")
   FimSe

Fimalgoritmo