Algoritmo "Comparaçao de inteiros"
//Escreva um algoritmo que leia dois números inteiros e compare-os, mostrando
//na tela uma das mensagens abaixo:
//- O primeiro valor é o maior
//- O segundo valor é o maior
//- Não existe valor maior, os dois são iguais

Var
   N1, N2: inteiro

Inicio
   Escreva ("Digite um número:")
   Leia (N1)
   Escreva ("Digite outro número:")
   Leia (N2)
   Se N1 > N2 entao
      Escreva ("O primeiro valor é maior")
   Senao
      Se N2 > N1 entao
         Escreva ("O segundo valor é maior")
      Senao
         Escreva ("Não existe valor maior, os dois são iguais")
      FimSe
   FimSe

Fimalgoritmo