Algoritmo "contador"
// Faça um algoritmo que pergunte ao usuário um número inteiro e positivo
//qualquer e mostre uma contagem até esse valor:
//Ex: Digite um valor: 35
//Contagem: 1 2 3 4 5 6 7 ... 33 34 35 Acabou!
Var
   contador: inteiro
   N: inteiro            // número escolhido

Inicio
   Escreva ("Digite um número inteiro, positivo:")
   Leia (N)
   contador <- 0
   Enquanto (contador <= N) faça
      EscrevaL (contador)
       contador <- contador + 1
      Se (contador > N) entao
         Escreva ("Acabou")
      FimSe
   FimEnquanto

Fimalgoritmo